# Generated by Django 5.1.3 on 2024-11-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expenses_incomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Leisure', 'Leisure'), ('Electronics', 'Electronics'), ('Utilities', 'Utilities'), ('Clothing', 'Clothing'), ('Health', 'Health'), ('Others', 'Others')], default='O', max_length=100),
        ),
    ]
