# Generated by Django 5.1.3 on 2024-11-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expenses_name_alter_expenses_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
