# Generated by Django 5.1.3 on 2024-11-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_incomes_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses-pics/'),
        ),
    ]
